/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    BottleHelperCard: typeof import('./src/components/cards/BottleHelperCard.vue')['default']
    BoxHelperCard: typeof import('./src/components/cards/BoxHelperCard.vue')['default']
    CarTaskCard: typeof import('./src/components/CarTaskCard.vue')['default']
    ChangelogCard: typeof import('./src/components/ChangelogCard.vue')['default']
    ClubBattleRecords: typeof import('./src/components/Club/ClubBattleRecords.vue')['default']
    ClubCarKing: typeof import('./src/components/ClubCarKing.vue')['default']
    ClubInfo: typeof import('./src/components/Club/ClubInfo.vue')['default']
    copy: typeof import('./src/components/cards/BoxHelperCard copy.vue')['default']
    DailyTaskCard: typeof import('./src/components/Daily/DailyTaskCard.vue')['default']
    DailyTaskStatus: typeof import('./src/components/Daily/DailyTaskStatus.vue')['default']
    FishHelperCard: typeof import('./src/components/cards/FishHelperCard.vue')['default']
    GameStatus: typeof import('./src/components/GameStatus.vue')['default']
    HangUpStatusCard: typeof import('./src/components/cards/HangUpStatusCard.vue')['default']
    IdentityCard: typeof import('./src/components/Common/IdentityCard.vue')['default']
    MessageTester: typeof import('./src/components/Test/MessageTester.vue')['default']
    MonthlyTasksCard: typeof import('./src/components/cards/MonthlyTasksCard.vue')['default']
    MyCard: typeof import('./src/components/Common/MyCard.vue')['default']
    Rank: typeof import('./src/components/Club/Rank.vue')['default']
    RoleProfileCard: typeof import('./src/components/Setting/RoleProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./src/components/Club/Signin.vue')['default']
    StudyChallengeCard: typeof import('./src/components/cards/StudyChallengeCard.vue')['default']
    TeamFormation: typeof import('./src/components/Team/TeamFormation.vue')['default']
    TeamStatus: typeof import('./src/components/Team/TeamStatus.vue')['default']
    ThemeToggle: typeof import('./src/components/Common/ThemeToggle.vue')['default']
    TokenManager: typeof import('./src/components/TokenManager.vue')['default']
    TowerStatus: typeof import('./src/components/Tower/TowerStatus.vue')['default']
    WebSocketTester: typeof import('./src/components/Test/WebSocketTester.vue')['default']
  }
}
